import * as XLSX from "xlsx";
import { mkdirSync, writeFileSync } from "node:fs";

// Deliberately synthetic QA content. This is not the required Spectora export.
const headers = [
  "Section Name",
  "Item Name",
  "Comment Name",
  "Comment Text",
  "Comment Type",
  "Order (w/i item)",
  "Answer Type",
  "Multiple Choice Options",
  "Default Value",
  "Default Estimate Min",
  "Default Estimate Max",
];
const rows: unknown[][] = [
  [
    "Roof",
    "Roof covering",
    "Asphalt shingle condition",
    "<p>The roof covering showed <strong>localized wear</strong> near the ridge. Review visible surfaces and document any damaged or missing shingles.</p><p>This is synthetic test material, not a property inspection.</p>",
    "info",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Roof",
    "Roof covering",
    "Damaged or missing shingles",
    '<p>Damaged or missing shingles may allow moisture intrusion. Recommend evaluation and repair by a qualified roofing contractor.</p><p><a href="https://www.nachi.org/roof-covering.htm">Roof covering reference</a></p>',
    "defect",
    2,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Roof",
    "Roof covering",
    "Inspection method",
    "<p>Roof surfaces were viewed from accessible areas. Portions obscured by debris were not inspected.</p>",
    "limit",
    3,
    "checkbox",
    "Ground, Ladder, Roof",
    "",
    "",
    "",
  ],
  [
    "Roof",
    "Roof drainage",
    "Gutter maintenance",
    "<p>Keep gutters clear and route downspouts away from the foundation.</p><ul><li>Remove debris</li><li>Check downspout extensions</li></ul>",
    "info",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Exterior",
    "Wall cladding",
    "Exterior overview",
    "<p>Inspect siding, trim, and penetrations for deterioration. Seal open joints as needed.</p>",
    "info",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Exterior",
    "Grading & drainage",
    "Surface drainage",
    "<p>Soil should promote drainage away from the structure. Review low spots after rainfall.</p>",
    "defect",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Plumbing",
    "Fixtures",
    "Fixture operation",
    "<p>Check representative fixtures for leaks and functional flow.</p>",
    "info",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Plumbing",
    "Water heater",
    "Water heater notes",
    "<p>Retain the <em>manufacturer’s instructions</em> and service history.</p>",
    "info",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Electrical",
    "Main panel",
    "Panel cover",
    "<p>Panel covers should be secured. Refer visible concerns to a qualified electrician.</p>",
    "defect",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
  [
    "Electrical",
    "Fixtures",
    "Testing limitation",
    "<p>Concealed wiring is outside the scope of this synthetic fixture.</p>",
    "limit",
    1,
    "text",
    "",
    "",
    "",
    "",
  ],
];
mkdirSync("tests/fixtures", { recursive: true });
for (const [name, data] of [
  ["synthetic-qa.xlsx", [headers, ...rows]],
  [
    "invalid-headers.xlsx",
    [
      ["Customer", "Invoice"],
      ["Example", "123"],
    ],
  ],
] as const) {
  const book = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    book,
    XLSX.utils.aoa_to_sheet(data.map((row) => [...row])),
    "Template",
  );
  writeFileSync(
    `tests/fixtures/${name}`,
    XLSX.write(book, { type: "buffer", bookType: "xlsx", bookSST: true }),
  );
}
console.log("Created clearly labeled synthetic and invalid QA fixtures.");
